# Generated by Django 3.2.8 on 2021-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название жанра'),
        ),
    ]
