# Generated by Django 3.2.8 on 2021-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название видео')),
                ('description', models.TextField(verbose_name='Описание видео')),
                ('genres', models.ManyToManyField(to='genres.Genre')),
            ],
        ),
    ]
