# Generated by Django 3.2.8 on 2021-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20211119_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название видео'),
        ),
    ]
