# Generated by Django 3.2.8 on 2021-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_alter_genre_title'),
        ('videos', '0003_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(to='genres.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название видео'),
        ),
    ]
